# Generated by Django 4.2.6 on 2023-10-15 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modelTest", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="image",
        ),
        migrations.RemoveField(
            model_name="student",
            name="roll",
        ),
    ]
