# Generated by Django 4.1.3 on 2023-10-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0002_recipe_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
