# Generated by Django 4.1.3 on 2023-10-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0006_studentmanagement_alter_student_managers_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentManagement",
        ),
        migrations.AlterModelManagers(
            name="student",
            managers=[],
        ),
    ]
